@startuml
!include  msdp/resources/C4-PlantUML-2.6.0/C4_Container.puml

fork
  partition "My Partition" {
    :Container(app, "Customer Application", "Javascript, Angular", "Allows customers to manage their profile");
  }
  partition "Another Partition" {
    :foo1;
    :foo2;
  }
endfork
fork
  partition "My Partition" {
    :Container(app, "Customer Application", "Javascript, Angular", "Allows customers to manage their profile");
  }
  partition "Another Partition" {
    :foo1;
    :foo2;
  }
endfork
@enduml
